---

hypervisor: aws # https://752625201053.signin.aws.amazon.com/console
remote_user:
  aws: centos #ubuntu ##ec2-user #centos

# aws_ami_id: "ami-06358f49b5839867c" #ubuntu 18.04
aws_ami_id: "ami-0ff760d16d9497662" # centos 7.7
# aws_region: "eu-west-1"
# aws_instance_state: absent # absent planned present

aws_region: "eu-west-1"
aws_instance_state: absent # present / absent

...
