---

- name: yum update
  yum:
    name: '*'
    state: latest
  become: true

- name: install apache 
  yum:
    name: httpd
  become: true

- name: create website configuration 
  template:
    src: a_website.conf.j2
    dest: /etc/httpd/conf.d/a_webstie.conf
  become: true

- name: copy html page 
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
  become: true

- name: restart webserver 
  service:
    name: httpd
    state: restarted
    enabled: yes
  become: true

...